--DROP TABLE personas
--DROP TABLE estados
SELECT * FROM estados;

CREATE TABLE estados(
    id_estado CHAR(1) NOT NULL,
    nombre_estado VARCHAR2(50) NOT NULL,
    descripcion_estado VARCHAR2(100),
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_estados PRIMARY KEY(id_estado)
);

CREATE TABLE personas(
    id_persona NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombres VARCHAR2(250) NOT NULL,
    apellidos VARCHAR2(250) NOT NULL,
    correo_electronico VARCHAR2(250),
    telefono VARCHAR2(15),
    celular VARCHAR2(15),
    estado CHAR(1) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_personas PRIMARY KEY(id_persona),
    CONSTRAINT fk_personas_estados FOREIGN KEY(estado) REFERENCES estados(id_estado)
);
COMMIT;
SELECT * FROM estados;
SELECT * FROM personas;

INSERT All 
INTO estados(id_estado,nombre_estado,descripcion_estado) 
VALUES ('A','Activo','Registro Activo')
INTO estados(id_estado,nombre_estado,descripcion_estado) 
VALUES ('I','Inactivo','Registro Inactivo')
SELECT * FROM dual;